### ISSUE TITLE
Request to add back license headers

### ISSUE THREAD

**Issue by Unpaid8503** [Favna/3DSThemeManager#1]
The removal of my own copyright notices is a violation of the GPLv3 and it is an infringement on my copyright. Fix this ASAP or I'll take action to take this repository down.

**Comment by favna** [comment]
Your life is an infringement of my oxygen but yes I am aware and plan to fix this after work tomorrow

**Comment by astronautlevel2** [comment]
Funny how you only care about GPLv3 issues when they're in your favor, and tried to ignore the issues with GPLv3 I brought up to you until I made them public. 

I already talked about this with Favna and he'll add them back in.

**Comment by fuckermansayin** [comment]
@ErmanSayin A present, just for you: https://notabug.org/fuckerman/3DSThemeManager - Removed your copyright-notice and commit history for free, never to be added back, good luck trying to take it down.

**Comment by ErmanSayin** [comment]
> good luck trying to take it down


![image](https://user-images.githubusercontent.com/5402062/29735810-26e98ece-89fc-11e7-9c04-c6a8955986ae.png)

didn't even take 30 mins

**Comment by astronautlevel2** [comment]
It's actually still u p as far as I can see.

**Comment by MissPotato** [comment]
@ErmanSayin Your GPLv3 license, you mean the open-source license? The one run by the community for the community? The one that has a FAQs on how it works, and one of them can be applied to this situation? 


> **Is the developer of a GPL-covered program bound by the GPL? Could the developer's actions ever be a violation of the GPL? (#DeveloperViolate)**
> 
> Strictly speaking, the GPL is a license from the developer for others to use, distribute and change the program. The developer itself is not bound by it, so no matter what the developer does, this is not a “violation” of the GPL.
> 
> However, if the developer does something that would violate the GPL if done by someone else, the developer will surely lose moral standing in the community.
> 

And further states that violations have a period in which they can be cured.

> **What does it mean to “cure” a violation of GPLv3? (https://www.gnu.org/licenses/gpl-faq.en.html#Cure)**
> To cure a violation means to adjust your practices to comply with the requirements of the license.

In fact, the license states Fevna has 30 days to fix this violation from the date and time (Aug 25, 2017, 4:55 PM EDT) to cure this violation.  (https://www.gnu.org/software/gnugo/gnugo_21.html)

**Comment by astronautlevel2** [comment]
@MissPotato Favna isn't the developer, erman is, so the whole first half is more or less irrelevant.

**Comment by zactekken** [comment]
AT LEAST FUCKING FIX THEMELY FOR RPWNG FAGS LIKE ME U FUCKING CUNT

**Comment by ErmanSayin** [comment]
@MissPotato this is not only a violation of the GPL, but also a copyright infringement.

**Comment by CodyMKW** [comment]
@zactekken lol caps

**Comment by zactekken** [comment]
LUL

**Comment by failzers** [comment]
What copyright exactly do you have?

**Comment by favna** [comment]
Fixed in 05e3e57ed142f832410e534a9e04c75f30c13f61 using [vscode extension licenser](https://marketplace.visualstudio.com/items?itemName=ymotongpoo.licenser)
